develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35733:35730"
  container_name: adapter-earth-engine-develop
  environment:
    ENVIRONMENT: dev
    DEBUG: "True"
    CT_URL: http://mymachine:9000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    LOCAL_URL: http://mymachine:5700
    EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
  command: develop
  volumes:
    - ./adapterearthengine:/opt/adapter-earth-engine/adapterearthengine
  restart: always
